- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Create ansible user
      user:
        name: ansible
        system: yes

    - name: Add ansible user to sudoers
      copy:
        src: files/sudoers_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: Create cache directory
      file:
        path: /home/ansible/.cache
        owner: ansible
        group: ansible
        state: directory
        mode: '0755'

    - name: Pull from repo every 20 minutes
      cron:
        user: ansible
        name: "ansible provision"
        minute: "*/20"
        job: "/usr/bin/ansible-pull -o -U https://github.com/victoitor/pargo-lab-ansible-pull.git > /dev/null"

    - name: Install packages
      apt:
        name:
          - htop
          - zsh
          - curl
          - build-essential
          - cmake
          - ninja-build
          - meson
          - pkg-config
          - neovim
          - 7zip
          - fzf
          - golang
          - python3
          - python3-pip
          - lsb

    - name: Set Python3 as default python executable
      community.general.alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/local/bin/python
        priority: 20

    - name: Download Epson printer driver
      get_url:
        url: https://download3.ebz.epson.net/dsc/f/03/00/14/48/15/1d37501ad39bd2b5753a9cce3b2715b3e2fef557/epson-inkjet-printer-escpr_1.7.26-1lsb3.2_amd64.deb
        dest: /home/ansible/.cache/epson-inkjet-printer-escpr_1.7.26-1lsb3.2_amd64.deb
        checksum: sha512:583f1afddc6004471794e66a6b47e9ef328d98203a63dd0bd6ae0bbe3fcd2b93be0c906151d30406874da93b32b3c9da0c3562e02e6b08ef43fecba8d8aadd7e

    - name: Install Epson escpr driver
      apt:
        deb: /home/ansible/.cache/epson-inkjet-printer-escpr_1.7.26-1lsb3.2_amd64.deb

    - name: Check if Epson printer is already added
      shell:
        cmd: lpstat -eE
      register: lpstat_out
      changed_when: False

    - name: Configure Epson L4260 printer
      shell:
        cmd: lpadmin -p ParGO-L4260 -v "lpd://10.102.54.103:515/PASSTHRU" -m "lsb/usr/epson-inkjet-printer-escpr/Epson/Epson-L4260_Series-epson-inkjet-printer-escpr.ppd.gz"
      when: lpstat_out.stdout.find('ParGO-L4260') == -1

