- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Create ansible user
      user:
        name: ansible
        system: yes

    - name: Add ansible user to sudoers
      copy:
        src: files/sudoers_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: Create cache directory
      file:
        path: /home/ansible/.cache
        owner: ansible
        group: ansible
        state: directory
        mode: '0755'

    - name: Add pargoldap to hosts
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: '(\s+)pargoldap\.ufc\.br(\s+)?$'
        line: '10.11.13.118    pargoldap.ufc.br'

    - name: Create homedir at login
      lineinfile:
        path: /etc/pam.d/common-session
        regexp: '^session\s+\w+\s+pam_mkhomedir\.so'
        line: 'session required         pam_mkhomedir.so skel=/etc/skel/ umask=0022'
        state: present

    - name: Install packages
      import_tasks:
        file: packages.yml

    - name: Install useful softwares
      import_tasks:
        file: install.yml

    - name: Pull from repo every 15 minutes
      cron:
        user: ansible
        name: "ansible provision"
        minute: "*/15"
        job: "/usr/bin/ansible-pull -o -U https://github.com/victoitor/pargo-lab-ansible-pull.git > /dev/null"

    - name: Add sssd configuration 
      copy: 
        src: files/pargoldap.conf
        dest: /etc/sssd/conf.d/pargoldap.conf
        owner: root
        group: root
        mode: 0600

    - name: Restart sssd service
      service:
        name: sssd
        state: restarted

    - name: Set Python3 as default python executable
      community.general.alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/local/bin/python
        priority: 20

    - name: Install Epson printer's driver
      import_task:
        file: epson.yml

    - name: Check if Epson printer is already added
      shell:
        cmd: lpstat -eE
      register: lpstat_out
      changed_when: False

    - name: Configure Epson L4260 printer
      shell:
        cmd: lpadmin -p ParGO-L4260 -v "lpd://10.102.54.103:515/PASSTHRU" -m "lsb/usr/epson-inkjet-printer-escpr/Epson/Epson-L4260_Series-epson-inkjet-printer-escpr.ppd.gz"
      when: lpstat_out.stdout.find('ParGO-L4260') == -1

    - name: Add Epson Scanner script
      copy:
        src: files/add-epson-scanner
        dest: /usr/local/bin/add-epson-scanner
        owner: root
        group: root
        mode: 0755

    - name: Add Epson Scanner on login (graphical)
      copy:
        src: files/epson-scanner.desktop
        dest: /etc/xdg/autostart/epson-scanner.desktop
        owner: root
        group: root
        mode: 0644

    - name: Add cluster access configuration
      copy:
        src: files/bastion-cluster.conf
        dest: /etc/ssh/ssh_config.d/bastion-cluster.conf
        owner: root
        group: root
        mode: 0644
